### ISSUE TITLE
Resulting uf2 does not work on Pico board

### ISSUE THREAD

**Issue by 42Bastian** [dougsummerville/elf2uf2#1]
Tried the current version. After putting the UF2 on the virtual disc, nothing happens.
I compared the resulting uf2 with the one from SDK and it differs in size and also the contents.

**Comment by dougsummerville** [comment]
> Tried the current version. After putting the UF2 on the virtual disc, nothing happens. I compared the resulting uf2 with the one from SDK and it differs in size and also the contents.

I do not use the SDK.  I've tested this against bare-metal ELF files generated by gcc, and it does produces identical UF2 files compared to the SDK C version.  Can you share the ELF file you tested, as well as the UF2 produced by the SDK utility?  I will see if I can track down the issue.

**Comment by 42Bastian** [comment]
Here the two uf2 and the original .elf file.
[hello.zip](https://github.com/dougsummerville/elf2uf2/files/10527446/hello.zip)

I use gcc 12.2.1 (if this makes a change).
Try 9.1.0, same.

**Comment by dougsummerville** [comment]
> Here the two uf2 and the original .elf file. [hello.zip](https://github.com/dougsummerville/elf2uf2/files/10527446/hello.zip)
> 
> I use gcc 12.2.1 (if this makes a change). Try 9.1.0, same.

Thank you for the files.  I believe the bug has been fixed.  It should generate an identical UF2.
